include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "lib/l10n/**"
  errors:
    # Treat these as warnings, not errors, during development
    todo: ignore
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Disable rules that conflict with our style
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_positional_boolean_parameters: false

    # Enable important rules
    avoid_print: true                    # Use logger instead
    avoid_dynamic_calls: true
    avoid_returning_null_for_future: true
    cancel_subscriptions: true
    close_sinks: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    use_build_context_synchronously: true

    # Security
    avoid_web_libraries_in_flutter: true
