// Placeholder for Firebase options
// This file will be generated by FlutterFire CLI:
// dart pub global activate flutterfire_cli
// flutterfire configure

// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
/// IMPORTANT: Replace with actual values from Firebase Console.
/// These are PLACEHOLDER values — replace before any production use.
///
/// To generate: run `flutterfire configure` in the app directory.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// PLACEHOLDER — replace with actual Firebase project values
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_ACTUAL_API_KEY',
    appId: '1:REPLACE:android:REPLACE',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'mystic-tarot-prod',
    storageBucket: 'mystic-tarot-prod.appspot.com',
  );

  /// PLACEHOLDER — replace with actual Firebase project values
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_ACTUAL_API_KEY',
    appId: '1:REPLACE:ios:REPLACE',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'mystic-tarot-prod',
    storageBucket: 'mystic-tarot-prod.appspot.com',
    iosBundleId: 'com.mystictarot.app',
  );
}
